---
- name: import zabbix db shcema
  mysql_db:
    login_host: "{{ zabbix_db_host }}"
    login_user: "{{ zabbix_db_user }}"
    login_password: "{{ zabbix_db_pwd }}"
    name: "{{ zabbix_db_name }}"
    target: "{{ item }}"
    state: import
  ignore_errors: True
  with_items: "{{ zabbix_db_shecma }}"

- name: configure zabbix-server
  template:
    src: zabbix_server.conf.j2
    dest: "{{ zabbix_server_config_path }}"
  notify:
    - restart zabbix server
