---
# tasks file for roles/zabbix

- include: install_repo.yml

- include: zabbix_server.yml
  when: zabbix_install_type == "server"

- include: zabbix_agent.yml
  when: zabbix_install_type == "agent"

- include: zabbix_web.yml
  when: zabbix_install_type == "web"
