---
# tasks file for roles/zabbix

- name: include install_repo.yml
  include: install_repo.yml

- name: include zabbix_server.yml when zabbix_install_type == 'server'
  include: zabbix_server.yml
  when: zabbix_install_type == "server"

- name: include zabbix_server.yml when zabbix_install_type == 'agent'
  include: zabbix_agent.yml
  when: zabbix_install_type == "agent"

- name: include zabbix_server.yml when zabbix_install_type == 'web'
  include: zabbix_web.yml
  when: zabbix_install_type == "web"
